/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FeedbackDothtmlRouteImport } from './routes/feedback[.]html'
import { Route as IndexDothtmlRouteImport } from './routes/index[.]html'
import { Route as OmOsRouteImport } from './routes/om-os'
import { Route as OmOsDothtmlRouteImport } from './routes/om-os[.]html'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivatlivRouteImport } from './routes/privatliv'
import { Route as PrivatlivDothtmlRouteImport } from './routes/privatliv[.]html'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SaleDothtmlRouteImport } from './routes/sale[.]html'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as Ugens_tilbudRouteImport } from './routes/ugens_tilbud'
import { Route as VilkaarDothtmlRouteImport } from './routes/vilkaar[.]html'
import { Route as ApiAutocompleteRouteImport } from './routes/api/autocomplete'
import { Route as ApiHomeRouteImport } from './routes/api/home'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiSaleRouteImport } from './routes/api/sale'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiStoresRouteImport } from './routes/api/stores'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as SearchResultsRouteImport } from './routes/search/results'
import { Route as ApiCategorySlugRouteImport } from './routes/api/category/$slug'
import { Route as ApiNutritionProductIdRouteImport } from './routes/api/nutrition/$productId'
import { Route as ApiPriceHistoryProductIdRouteImport } from './routes/api/price-history/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackDothtmlRoute = FeedbackDothtmlRouteImport.update({
  id: '/feedback.html',
  path: '/feedback.html',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDothtmlRoute = IndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOsRoute = OmOsRouteImport.update({
  id: '/om-os',
  path: '/om-os',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOsDothtmlRoute = OmOsDothtmlRouteImport.update({
  id: '/om-os.html',
  path: '/om-os.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatlivRoute = PrivatlivRouteImport.update({
  id: '/privatliv',
  path: '/privatliv',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatlivDothtmlRoute = PrivatlivDothtmlRouteImport.update({
  id: '/privatliv.html',
  path: '/privatliv.html',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleDothtmlRoute = SaleDothtmlRouteImport.update({
  id: '/sale.html',
  path: '/sale.html',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const Ugens_tilbudRoute = Ugens_tilbudRouteImport.update({
  id: '/ugens_tilbud',
  path: '/ugens_tilbud',
  getParentRoute: () => rootRouteImport,
} as any)
const VilkaarDothtmlRoute = VilkaarDothtmlRouteImport.update({
  id: '/vilkaar.html',
  path: '/vilkaar.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutocompleteRoute = ApiAutocompleteRouteImport.update({
  id: '/api/autocomplete',
  path: '/api/autocomplete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeRoute = ApiHomeRouteImport.update({
  id: '/api/home',
  path: '/api/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaleRoute = ApiSaleRouteImport.update({
  id: '/api/sale',
  path: '/api/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoresRoute = ApiStoresRouteImport.update({
  id: '/api/stores',
  path: '/api/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchResultsRoute = SearchResultsRouteImport.update({
  id: '/search/results',
  path: '/search/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategorySlugRoute = ApiCategorySlugRouteImport.update({
  id: '/api/category/$slug',
  path: '/api/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNutritionProductIdRoute = ApiNutritionProductIdRouteImport.update({
  id: '/api/nutrition/$productId',
  path: '/api/nutrition/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPriceHistoryProductIdRoute =
  ApiPriceHistoryProductIdRouteImport.update({
    id: '/api/price-history/$productId',
    path: '/api/price-history/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRoute
  '/about': typeof AboutRoute
  '/feedback': typeof FeedbackRoute
  '/feedback.html': typeof FeedbackDothtmlRoute
  '/index.html': typeof IndexDothtmlRoute
  '/om-os': typeof OmOsRoute
  '/om-os.html': typeof OmOsDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/privatliv': typeof PrivatlivRoute
  '/privatliv.html': typeof PrivatlivDothtmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sale.html': typeof SaleDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/ugens_tilbud': typeof Ugens_tilbudRoute
  '/vilkaar.html': typeof VilkaarDothtmlRoute
  '/api/autocomplete': typeof ApiAutocompleteRoute
  '/api/home': typeof ApiHomeRoute
  '/api/products': typeof ApiProductsRoute
  '/api/sale': typeof ApiSaleRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stores': typeof ApiStoresRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/search/results': typeof SearchResultsRoute
  '/search/': typeof SearchIndexRoute
  '/api/category/$slug': typeof ApiCategorySlugRoute
  '/api/nutrition/$productId': typeof ApiNutritionProductIdRoute
  '/api/price-history/$productId': typeof ApiPriceHistoryProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRoute
  '/about': typeof AboutRoute
  '/feedback': typeof FeedbackRoute
  '/feedback.html': typeof FeedbackDothtmlRoute
  '/index.html': typeof IndexDothtmlRoute
  '/om-os': typeof OmOsRoute
  '/om-os.html': typeof OmOsDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/privatliv': typeof PrivatlivRoute
  '/privatliv.html': typeof PrivatlivDothtmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sale.html': typeof SaleDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/ugens_tilbud': typeof Ugens_tilbudRoute
  '/vilkaar.html': typeof VilkaarDothtmlRoute
  '/api/autocomplete': typeof ApiAutocompleteRoute
  '/api/home': typeof ApiHomeRoute
  '/api/products': typeof ApiProductsRoute
  '/api/sale': typeof ApiSaleRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stores': typeof ApiStoresRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/search/results': typeof SearchResultsRoute
  '/search': typeof SearchIndexRoute
  '/api/category/$slug': typeof ApiCategorySlugRoute
  '/api/nutrition/$productId': typeof ApiNutritionProductIdRoute
  '/api/price-history/$productId': typeof ApiPriceHistoryProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category': typeof CategoryRoute
  '/about': typeof AboutRoute
  '/feedback': typeof FeedbackRoute
  '/feedback.html': typeof FeedbackDothtmlRoute
  '/index.html': typeof IndexDothtmlRoute
  '/om-os': typeof OmOsRoute
  '/om-os.html': typeof OmOsDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/privatliv': typeof PrivatlivRoute
  '/privatliv.html': typeof PrivatlivDothtmlRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sale.html': typeof SaleDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/ugens_tilbud': typeof Ugens_tilbudRoute
  '/vilkaar.html': typeof VilkaarDothtmlRoute
  '/api/autocomplete': typeof ApiAutocompleteRoute
  '/api/home': typeof ApiHomeRoute
  '/api/products': typeof ApiProductsRoute
  '/api/sale': typeof ApiSaleRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stores': typeof ApiStoresRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/search/results': typeof SearchResultsRoute
  '/search/': typeof SearchIndexRoute
  '/api/category/$slug': typeof ApiCategorySlugRoute
  '/api/nutrition/$productId': typeof ApiNutritionProductIdRoute
  '/api/price-history/$productId': typeof ApiPriceHistoryProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$category'
    | '/about'
    | '/feedback'
    | '/feedback.html'
    | '/index.html'
    | '/om-os'
    | '/om-os.html'
    | '/privacy'
    | '/privatliv'
    | '/privatliv.html'
    | '/robots.txt'
    | '/sale.html'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/ugens_tilbud'
    | '/vilkaar.html'
    | '/api/autocomplete'
    | '/api/home'
    | '/api/products'
    | '/api/sale'
    | '/api/search'
    | '/api/stores'
    | '/product/$productId'
    | '/search/results'
    | '/search/'
    | '/api/category/$slug'
    | '/api/nutrition/$productId'
    | '/api/price-history/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$category'
    | '/about'
    | '/feedback'
    | '/feedback.html'
    | '/index.html'
    | '/om-os'
    | '/om-os.html'
    | '/privacy'
    | '/privatliv'
    | '/privatliv.html'
    | '/robots.txt'
    | '/sale.html'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/ugens_tilbud'
    | '/vilkaar.html'
    | '/api/autocomplete'
    | '/api/home'
    | '/api/products'
    | '/api/sale'
    | '/api/search'
    | '/api/stores'
    | '/product/$productId'
    | '/search/results'
    | '/search'
    | '/api/category/$slug'
    | '/api/nutrition/$productId'
    | '/api/price-history/$productId'
  id:
    | '__root__'
    | '/'
    | '/$category'
    | '/about'
    | '/feedback'
    | '/feedback.html'
    | '/index.html'
    | '/om-os'
    | '/om-os.html'
    | '/privacy'
    | '/privatliv'
    | '/privatliv.html'
    | '/robots.txt'
    | '/sale.html'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/ugens_tilbud'
    | '/vilkaar.html'
    | '/api/autocomplete'
    | '/api/home'
    | '/api/products'
    | '/api/sale'
    | '/api/search'
    | '/api/stores'
    | '/product/$productId'
    | '/search/results'
    | '/search/'
    | '/api/category/$slug'
    | '/api/nutrition/$productId'
    | '/api/price-history/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRoute
  AboutRoute: typeof AboutRoute
  FeedbackRoute: typeof FeedbackRoute
  FeedbackDothtmlRoute: typeof FeedbackDothtmlRoute
  IndexDothtmlRoute: typeof IndexDothtmlRoute
  OmOsRoute: typeof OmOsRoute
  OmOsDothtmlRoute: typeof OmOsDothtmlRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivatlivRoute: typeof PrivatlivRoute
  PrivatlivDothtmlRoute: typeof PrivatlivDothtmlRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SaleDothtmlRoute: typeof SaleDothtmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  Ugens_tilbudRoute: typeof Ugens_tilbudRoute
  VilkaarDothtmlRoute: typeof VilkaarDothtmlRoute
  ApiAutocompleteRoute: typeof ApiAutocompleteRoute
  ApiHomeRoute: typeof ApiHomeRoute
  ApiProductsRoute: typeof ApiProductsRoute
  ApiSaleRoute: typeof ApiSaleRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiStoresRoute: typeof ApiStoresRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  SearchResultsRoute: typeof SearchResultsRoute
  SearchIndexRoute: typeof SearchIndexRoute
  ApiCategorySlugRoute: typeof ApiCategorySlugRoute
  ApiNutritionProductIdRoute: typeof ApiNutritionProductIdRoute
  ApiPriceHistoryProductIdRoute: typeof ApiPriceHistoryProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback.html': {
      id: '/feedback.html'
      path: '/feedback.html'
      fullPath: '/feedback.html'
      preLoaderRoute: typeof FeedbackDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.html': {
      id: '/index.html'
      path: '/index.html'
      fullPath: '/index.html'
      preLoaderRoute: typeof IndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-os': {
      id: '/om-os'
      path: '/om-os'
      fullPath: '/om-os'
      preLoaderRoute: typeof OmOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-os.html': {
      id: '/om-os.html'
      path: '/om-os.html'
      fullPath: '/om-os.html'
      preLoaderRoute: typeof OmOsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatliv': {
      id: '/privatliv'
      path: '/privatliv'
      fullPath: '/privatliv'
      preLoaderRoute: typeof PrivatlivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatliv.html': {
      id: '/privatliv.html'
      path: '/privatliv.html'
      fullPath: '/privatliv.html'
      preLoaderRoute: typeof PrivatlivDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale.html': {
      id: '/sale.html'
      path: '/sale.html'
      fullPath: '/sale.html'
      preLoaderRoute: typeof SaleDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ugens_tilbud': {
      id: '/ugens_tilbud'
      path: '/ugens_tilbud'
      fullPath: '/ugens_tilbud'
      preLoaderRoute: typeof Ugens_tilbudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vilkaar.html': {
      id: '/vilkaar.html'
      path: '/vilkaar.html'
      fullPath: '/vilkaar.html'
      preLoaderRoute: typeof VilkaarDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autocomplete': {
      id: '/api/autocomplete'
      path: '/api/autocomplete'
      fullPath: '/api/autocomplete'
      preLoaderRoute: typeof ApiAutocompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/home': {
      id: '/api/home'
      path: '/api/home'
      fullPath: '/api/home'
      preLoaderRoute: typeof ApiHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sale': {
      id: '/api/sale'
      path: '/api/sale'
      fullPath: '/api/sale'
      preLoaderRoute: typeof ApiSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stores': {
      id: '/api/stores'
      path: '/api/stores'
      fullPath: '/api/stores'
      preLoaderRoute: typeof ApiStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/results': {
      id: '/search/results'
      path: '/search/results'
      fullPath: '/search/results'
      preLoaderRoute: typeof SearchResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/category/$slug': {
      id: '/api/category/$slug'
      path: '/api/category/$slug'
      fullPath: '/api/category/$slug'
      preLoaderRoute: typeof ApiCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nutrition/$productId': {
      id: '/api/nutrition/$productId'
      path: '/api/nutrition/$productId'
      fullPath: '/api/nutrition/$productId'
      preLoaderRoute: typeof ApiNutritionProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/price-history/$productId': {
      id: '/api/price-history/$productId'
      path: '/api/price-history/$productId'
      fullPath: '/api/price-history/$productId'
      preLoaderRoute: typeof ApiPriceHistoryProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRoute,
  AboutRoute: AboutRoute,
  FeedbackRoute: FeedbackRoute,
  FeedbackDothtmlRoute: FeedbackDothtmlRoute,
  IndexDothtmlRoute: IndexDothtmlRoute,
  OmOsRoute: OmOsRoute,
  OmOsDothtmlRoute: OmOsDothtmlRoute,
  PrivacyRoute: PrivacyRoute,
  PrivatlivRoute: PrivatlivRoute,
  PrivatlivDothtmlRoute: PrivatlivDothtmlRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SaleDothtmlRoute: SaleDothtmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  Ugens_tilbudRoute: Ugens_tilbudRoute,
  VilkaarDothtmlRoute: VilkaarDothtmlRoute,
  ApiAutocompleteRoute: ApiAutocompleteRoute,
  ApiHomeRoute: ApiHomeRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiSaleRoute: ApiSaleRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiStoresRoute: ApiStoresRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  SearchResultsRoute: SearchResultsRoute,
  SearchIndexRoute: SearchIndexRoute,
  ApiCategorySlugRoute: ApiCategorySlugRoute,
  ApiNutritionProductIdRoute: ApiNutritionProductIdRoute,
  ApiPriceHistoryProductIdRoute: ApiPriceHistoryProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
